site_name: LEarn Anything
site_url: https://docs.learn-anything.vn
site_description: >-
  Ignite curiosity. Inspire learning.
theme:
  custom_dir: docs/material/overrides
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/knowledge.png
  favicon: assets/images/knowledge.png
  font:
    text: Plus Jakarta Sans
    code: Roboto Mono
  palette: 
    - scheme: default
      primary: vnstock
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for light mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - toc.integrate # tắt để hiện riêng bên thanh bên phải
    - navigation.top
  # language: en
extra_css:
  - stylesheets/extra.css
edit_uri: edit/main/docs/docs                 
plugins:
  - glightbox
  # - search
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social: # display a preview on social for links
      # cards_layout: default 
  # - meta # blog metadata
  - blog:
      enabled: true
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 2
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_excerpt: optional
      post_excerpt_max_categories: 2
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 300
      categories: true
      categories_name: Danh mục
      categories_url_format: "category/{slug}"
      categories_toc: true
      archive: true
      archive_name: Dòng thời gian
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"
      archive_toc: true
      # categories_allowed:
      #   - hướng dẫn
      #   - kiến thức
      #   - How to
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 


markdown_extensions:
  - toc:
      permalink: true
      title: Mục lục
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # button
  - attr_list
  # annotations
  - md_in_html
  - pymdownx.superfences
  # footnotes
  - footnotes
  # markdown formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # tooltips
  - abbr
  - attr_list
  - pymdownx.snippets
  # list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # database
  - tables
  # content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # image
  - attr_list
  - md_in_html
  # mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    # provider: google
    # property: G-DJT4KFYTW8
    provider: custom
    property: Google Tag Manager
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@learn_anything_az?sub_confirmation=1
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/learn.anything.az
    - icon: fontawesome/solid/bookmark
      link: https://learnanything.substack.com/
    - icon: fontawesome/solid/globe
      link: https://learn-anything.vn
  generator: false
  # alternate:
  # - name: English
  #   link: /en/ 
  #   lang: en
  # - name: Việt Nam
  #   link: /vi/
  #   lang: vi
# repo_name: vnstock
# repo_url: https://github.com/thinh-vu/vnstock
# copyright: Copyright &copy; 2023 | vnstock.site

# Page tree
nav:
  - Trang chủ: index.md
  - Giới thiệu: 
    - Bắt đầu: gioi-thieu/index.md
    # - Lịch sử cập nhật: gioi-thieu/changes_log.md
    - Trích dẫn: gioi-thieu/cite.md
  - Obsidian: kien-thuc/obsidian/hoc-obsidian-cung-learn-anything.md
  # - Python: kien-thuc/python/hoc-python-cung-learn-anything.md
  # - Prompt Engineering: kien-thuc/AI/huong-dan-ky-nang-prompt-engineering.md
  - Khóa học: khoa-hoc/hoc-tap-cung-learn-anything.md
  - Blog: blog/index.md
  # - Python:
  # - Data:
  # - Công nghệ: